### ISSUE TITLE
[Request] Add some usage examples to Readme.

### ISSUE THREAD

**Issue by mesqueeb** [rmmmp/mock-cloud-firestore#24]
I am looking for a Firestore Mock I can use to test an api wrapper I wrote around firestore batch update and delete functionalities. I'd love a few simple examples of how we can use this mock! Cheers!!

**Comment by rmmmp** [comment]
*Replacing the Firebase instance depends on how your app consumes it. As an example, you could do window.firebase = new MockFirebase(fixtureData) on a browser environment.*

I'll be happy to change things if what I wrote above doesn't help. I'm just unsure yet what can be the most generic way to give as an example since it really depends on how your app consumes Firebase.

Examples:

1. You use it as a global variable. So in this case, simply doing `window.firebase = new MockFirebase(fixtureData)` should work.
2. You use it as an `import` (e.g. `import firebase from 'firebase'`). So in this case, I believe it's the same as #1.
3. You're passing in `firebase` as an argument to a function. So in this case, simply pass-in `new MockFirebase(fixtureData)` as the argument to that function.

**Comment by mesqueeb** [comment]
Cool, I'm trying to play around with the mock this week. 
Thing I'm worried about integration with the mock is what I'm doing here:
```js
      dbRef
      .onSnapshot(querySnapshot => {
        let source = querySnapshot.metadata.hasPendingWrites ? 'local' : 'server'
        querySnapshot.docChanges().forEach(change => {
          const doc = change.doc.data()
          handleDoc(change, id, doc, source)
```
In this example when the user launches the app, this is how I get all the initial docs from the user that's logged in.
I could ignore userId's and just have a generic `dbRef` for tests.

I add each doc to a shared store (vuex) with the `handleDoc` function. But I read that there's limited support for `querySnapshot.docChanges().forEach`?

**Comment by rmmmp** [comment]
Yes. `docChanges()` isn't supported at the moment. I personally haven't used that API before but based from what I can see in the docs, that's something that goes hand-in-hand with realtime queries (which is also not supported at the moment).

**Comment by rmmmp** [comment]
I think the easiest way would be is to add some placeholder functions and properties (e.g. for `docChanges` and `metadata`). So that the code will just passthrough them.

I'll try to get them done within the week. Though if you have time, I welcome PRs. :wink:

**Comment by mesqueeb** [comment]
@rmmmp I haven't been able to setup a test yet using your library.

However, I've run into really bad situations, not having enough tests on my library!
The things I would need to test are actions inside my app that require quite a few firebase specific things, since firebase is a dependency.

Could you help me out a little bit and tell me how do I change these lines out of my original source to be able to test with your library?

- `if (Firebase.auth().currentUser) state._sync.signedIn = true`
- `if (!Firebase.auth().currentUser) return false`
- `Firebase.firestore().batch()`
- `Firebase.firestore.FieldValue.serverTimestamp()`
- `Firebase.firestore.FieldValue.delete()`
and
```js
return (getters.collectionMode)
      ? Firebase.firestore().collection(path)
      : Firebase.firestore().doc(path)
```

These are all the locations I use firebase in the app, so just switching out these should do the trick.

PS: what is your recommended way to actually switch out Firebase for the mock? Do you edit the code, make a build specially for tests, then change the code back to using the original firebase for production?

Thanks so much!!

**Comment by rmmmp** [comment]
Your question is actually more of related to testing rather than for this library. Basically, there are certain patterns that you can use to architect your code in order to make it testable. One pattern would be *dependency injection*.

Basically, you pass-in the firebase instance as a parameter in your functions. So that when you test those certain functions, you can mock the firebase instance that you're passing in.

e.g.

```javascript
class Foo {
  bar(firebase) {
    return firebase.firestore().collection('users').get();
  }
}
```

To test that `bar()` function, you need to pass-in `new MockFirebase(fixtureData)` to it.

**Comment by mesqueeb** [comment]
@rmmmp Sorry for the trouble!  : S and thanks for helping me out with this!
I will refactor my library to pass firestore as parameter, use your mock and then report on how it went!

If all went well I'll try to contribute a small section to the ReadMe with some examples easy to understand to users still quite new to testing. : )
