### ISSUE TITLE
merge with firebase-mock

### ISSUE THREAD

**Issue by soumak77** [rmmmp/mock-cloud-firestore#29]
I'm wondering whether you would like to merge this library with [firebase-mock](https://github.com/soumak77/firebase-mock).  I am the developer of that project and would be happy to assist in any way to help merge the feature set from this library.  From what I can tell the only key difference is in how you initialize your dataset.  Once the data is initialized, the libraries appear to be very similar.  There may be some [outstanding issues](https://github.com/soumak77/firebase-mock/issues) which prevent you from wanting to switch mocking libraries, but I'm sure we can work through them.

**Comment by rmmmp** [comment]
I'd love to but unfortunately I wouldn't be able to help that much with the merging. I quickly hacked this before for my personal use and only touch this library when really needed due to lack of time.

I read somewhere in stackoverflow that the Firebase team has a mocking library in their pipeline so I've just been using this for the meantime until that official library pops up.

**Comment by soumak77** [comment]
I didn't know firebase had plans to provide a mocking library.  Thanks for the consideration.

**Comment by rmmmp** [comment]
[Here's](https://stackoverflow.com/questions/46563885/running-firestore-local-e-g-for-testing) a reference to what I'm saying. That's way back in 2017 so... 😞

**Comment by Venryx** [comment]
Hmm, a clear difference seems to be that `firebase-mock` must be run in NodeJS (ie. with access to the "fs" module), whereas `mock-cloud-firestore` can run entirely in the browser.

Is this distinction accurate, or am I misunderstanding?

Anyway, if true, this makes `mock-cloud-firestore` better for my use-case, because it means I can more easily integrate the mocking library with [Cypress](https://docs.cypress.io/guides/overview/key-differences.html#Architecture). (Cypress tests run in the browser alongside the main application code)

If so, would be nice to have a mention of this distinction somewhere, as it's led to quite a bit of confusion as I've evaluated the different firestore-mocking options.

1) firebase-mock (NodeJS required)
2) mock-cloud-firestore
3) firebase-server (Firebase only)
4) [Cloud Firestore Emulator](https://firebase.google.com/docs/firestore/security/test-rules-emulator)

**Comment by Venryx** [comment]
On looking closer at `firebase-mock`, it looks like the uses of `fs` are just for some extra features like downloading files? If so, is there a way to exclude that portion of the library? At the moment, it's causing Webpack errors when attempting to import `firebase-mock` from in-browser code.

**Comment by mikkopaderes** [comment]
I'm not the maintainer nor a user of `firebase-mock` so I can't answer your question for that.

For the distinction, yes this library is suited to run in the browser and nodejs. However, I recommend using the firestore emulator in nodejs as that's the official testing solution for it. That's also the reason why I'll be reluctant on adding nodejs specific API if any in the future.
